### ISSUE TITLE
Is there any way to hide what my "real" email address is

### ISSUE THREAD

**Issue by WELZ-gh** [forwardemail/free-email-forwarding#191] opened 2019-12-09 01:44 UTC
The issue is that anybody can do a quick dns lookup for my domain and view all the txt records, is there another way to "hide" my "real" email address?

Is this something in the future roadmap?

![image](https://user-images.githubusercontent.com/35234925/70400979-84940400-19fb-11ea-8e40-9fe95a886cc5.png)

**Comment by travi** [comment] 2019-12-09 02:14
https://github.com/forwardemail/free-email-forwarding/issues/6

**Comment by allanlaal** [comment] 2019-12-31 18:24
yeah, duplicate of #6

**Comment by niftylettuce** [comment] 2020-02-06 12:30
This feature is now available (FOR FREE) at https://forwardein beta program (ignore the pricing, as it's free for the beta program, then after beta program is over, you will have 30 days to enter billing info).

You can easily import existing TXT records with 1-click using the "Import TXT" button in the Alias Manager.

Try it out! https://forwardemail.net/features

Feedback is welcome.

🎉

**Closed by niftylettuce** 2020-02-06 12:30 UTC
