### ISSUE TITLE
Emails not getting delivered from certain senders

### ISSUE THREAD

**Issue by elsiehupp** [forwardemail/free-email-forwarding#192] opened 2019-12-12 19:17 UTC
I created unique email addresses for my accounts with both Autodesk and Adobe, but the verification emails do not seem to have been delivered, even with repeated attempts. When I send emails to myself at those email addresses, my test emails do get delivered. The missing emails do not appear in my spam folder. Some email senders do work, but not these two.

Might this be an issue with one or another of forward-email's anti-spam features? My issue seems similar to #183. 

(FYI my domain is elsiehupp.com. The emails getting bounced are from automated systems, so there's no way for me to see them.)

**Comment by niftylettuce** [comment] 2019-12-13 06:31
I have confirmed Amazon.com and Adobe.com are not passing DKIM tests.  I will fix immediately after investigation and report back to you.

**Comment by niftylettuce** [comment] 2019-12-13 09:11
OK I figured out the issue.  Python 2.7 DNS lookup does not recursively crawl TXT when there is a CNAME reference.  Python 3 DNS lookup fixes this.  I've emailed the authors of `dkimpy` package so they are aware of this issue.

```sh
dig jvxsykglqiaiibkijmhy37vqxh4mzqr6._domainkey.amazon.com. txt

; <<>> DiG 9.8.3-P1 <<>> jvxsykglqiaiibkijmhy37vqxh4mzqr6._domainkey.amazon.com. txt
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57307
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
; OPT=12: 00 00 00 00  (.) (.) (.) (.)
;; QUESTION SECTION:
;jvxsykglqiaiibkijmhy37vqxh4mzqr6._domainkey.amazon.com. IN TXT

;; ANSWER SECTION:
jvxsykglqiaiibkijmhy37vqxh4mzqr6._domainkey.amazon.com. 528 IN CNAME jvxsykglqiaiibkijmhy37vqxh4mzqr6.dkim.amazonses.com.
jvxsykglqiaiibkijmhy37vqxh4mzqr6.dkim.amazonses.com. 528 IN TXT "p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCattwErMzn3tJ9L4fcHF3+TjVYoLuxXAuBYDfy1pb4ZyWoxy9ddAn060lGRxLAgS2ehuaLwO8OX7gmeAtTO3mrTSE3m752ClorWO1lqBh+Cruj3CnFPVD8u2YqjY5kreJGkjAbd0vtMMTGHvUIJ0e/fkXHZXCOGXkj5NXyCAAo1wIDAQAB"

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Dec 13 02:50:52 2019
;; MSG SIZE  rcvd: 384
```

The `get_txt` method isn't following the CNAME recursive lookup.  I tested this on Python v3 and the signature works OK.  This is only on Python v2.7.

I am working on implementing the fix and deploying it now.

**Comment by elsiehupp** [comment] 2019-12-13 12:20
Yay! Thank you for responding so quickly! The inner workings of email is still kind of voodoo for me. For what it's worth, I have yet to get any of my DMARC summaries from Postmark, either. It would be somewhat ironic if they were failing DKIM tests, as well, don't you think? 😅

**Comment by themew** [comment] 2019-12-13 21:59
Looks like email forwarding stopped around 2:20am CT.  We fwd 4 email addresses on 2 domains through the mx service offered and still nothing arrives.  
Best of luck getting things back up and running -- it's been such a great service!

**Comment by original-dotexe** [comment] 2019-12-13 22:43
yeah my emails are not coming/going through either. just getting DKIM verification errors or sometimes I just get nothing at all. hopefully it can be fixed soon.

**Comment by niftylettuce** [comment] 2019-12-13 22:43
I am working on this right now.

**Comment by original-dotexe** [comment] 2019-12-13 22:44
sweet. hopefully it will be fixed soon :)

**Comment by niftylettuce** [comment] 2019-12-13 23:23
All fixed.  Adobe and Amazon emails should be flowing through now.

I will commit the code in a bit, have to run an errand, but the code is patched manually on all servers!

**Closed by niftylettuce** 2019-12-13 23:23 UTC

**Comment by themew** [comment] 2019-12-13 23:30
Awesome. Thanks @niftylettuce , they're flowing into gmail again!  :)

**Comment by original-dotexe** [comment] 2019-12-13 23:31
yep it's working great for me too. awesome that you got that fixed so fast :)))

**Comment by elsiehupp** [comment] 2019-12-14 00:39
Thanks for addressing this so quickly! Autodesk's verification email is making it through, now, but Adobe's is still not working... Any thoughts on that?

**Comment by niftylettuce** [comment] 2019-12-14 03:05
@elsiehupp are you sure?  did you try resending verification code?  I got Adobe emails just fine as a test run.

<img width="971" alt="Screen Shot 2019-12-13 at 9 04 58 PM" src="https://user-images.githubusercontent.com/523141/70842683-40827400-1dec-11ea-8f30-01948029a166.png">

If you continue to have issues toss me an email at niftylettuce@gmail.com with what address you're sending to

**Comment by elsiehupp** [comment] 2019-12-15 06:01
I tried again today, and it worked. I guess the changes just took a little time to percolate. (The other thing I tried was I changed my Adobe ID back to my personal email before changing it again to my new forwarding email, which may have reset something or other behind the scenes on Adobe's side.) Thank you again for your prompt attention on this issue!
