### ISSUE TITLE
Some email-providers don't show the email of the sender

### ISSUE THREAD

**Issue by leonheess** [forwardemail/free-email-forwarding#148] opened 2019-07-05 16:21 UTC
I found another small issue where I'm unsure if something can be done about it. Some big name email-providers (eg. web.de) do not show the sender's email. As far as I understand it you include the email within the senders name like so 

    Name: "Display Name" <mail@example.com> 
    Email: no-reply@forwardemail.net

but these email-providers somehow only show the following for what I assume anti-scam reasons:

    Name: "Display Name"
    Email: no-reply@forwardemail.net

Screenshot of an example:
![Screenshot_20190705-181220(1)](https://user-images.githubusercontent.com/13834296/60735053-31042280-9f52-11e9-85ef-10ede7cf3aac.jpg)

This can be closed if nothing can be done about it but maybe the formatting is all that needs to be changed.

Possible ideas for Name:
• "Display Name \<mail@example.com\>"
• "Display Name" mail@example.com
• "Display Name mail@example.com"
• "Display Name mail(at)example.com"

**Comment by gabrielpb1** [comment] 2019-07-17 00:48
Same issue with Protonmail

**Comment by allanlaal** [comment] 2019-09-07 21:51
same issue with Gmail

**Comment by emilstahl** [comment] 2019-11-18 22:17
Not an issue, but expected behavior when you receive mail from a domain with a DMARC policy.

> DMARC - we check if a DMARC record exists from the sender's FQDN, and if so, if it is reject or quarantine then we re-write the From of the email as a "friendly-from". This means the From is set to $originalName <no-reply@forwardemail.net> ($originalName is the original From name, e.g. "John Doe" in "John Doe john@domain.com"). Furthermore we set a Reply-To (if one is not already set) of the original sender's from address.

https://forwardemail.net/#/?id=how-do-you-prevent-spammers-and-ensure-good-email-forwarding-reputation

**Comment by leonheess** [comment] 2019-11-19 07:36
@emilstahl expected behavior ≠ useful/wanted behavior

**Comment by fbartels** [comment] 2020-02-13 07:54
Duplicate of https://github.com/forwardemail/free-email-forwarding/issues/137#issuecomment-582695721

**Closed** 2020-02-18 08:18 UTC

**Comment by niftylettuce** [comment] 2020-02-18 08:24
Released as of v6.0.0 and just deployed to all production mail exchange servers.  This should go into effect immediately, and you should no longer have `no-reply@forwardemail.net` nor friendly-from rewrites with a "Reply-To" header being added to your forwarded emails.

As always, thanks for your patience, let me know of any issues, and please consider upgrading to a paid plan or making a donation.

https://forwardemail.net/features
https://forwardemail.net/donate
